[2023-07-28T14:21:55.848+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: monthly_statistics.preprocess_and_convert_to_euro manual__2023-07-28T12:21:52.576533+00:00 [queued]>
[2023-07-28T14:21:55.854+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: monthly_statistics.preprocess_and_convert_to_euro manual__2023-07-28T12:21:52.576533+00:00 [queued]>
[2023-07-28T14:21:55.854+0200] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-28T14:21:55.862+0200] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): preprocess_and_convert_to_euro> on 2023-07-28 12:21:52.576533+00:00
[2023-07-28T14:21:55.865+0200] {standard_task_runner.py:57} INFO - Started process 16613 to run task
[2023-07-28T14:21:55.869+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'monthly_statistics', 'preprocess_and_convert_to_euro', 'manual__2023-07-28T12:21:52.576533+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/monthly_statistics.py', '--cfg-path', '/var/folders/s3/52f8ptfd1wg8m_7fvtgb9g0w0000gn/T/tmp9zjassy3']
[2023-07-28T14:21:55.870+0200] {standard_task_runner.py:85} INFO - Job 6: Subtask preprocess_and_convert_to_euro
[2023-07-28T14:21:55.922+0200] {task_command.py:410} INFO - Running <TaskInstance: monthly_statistics.preprocess_and_convert_to_euro manual__2023-07-28T12:21:52.576533+00:00 [running]> on host gabriel-3.home
[2023-07-28T14:21:56.002+0200] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='monthly_statistics' AIRFLOW_CTX_TASK_ID='preprocess_and_convert_to_euro' AIRFLOW_CTX_EXECUTION_DATE='2023-07-28T12:21:52.576533+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-28T12:21:52.576533+00:00'
[2023-07-28T14:21:56.004+0200] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/opt/homebrew/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: preprocess_and_convert_to_euro() missing 1 required positional argument: 'df'
[2023-07-28T14:21:56.017+0200] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=monthly_statistics, task_id=preprocess_and_convert_to_euro, execution_date=20230728T122152, start_date=20230728T122155, end_date=20230728T122156
[2023-07-28T14:21:56.025+0200] {standard_task_runner.py:104} ERROR - Failed to execute job 6 for task preprocess_and_convert_to_euro (preprocess_and_convert_to_euro() missing 1 required positional argument: 'df'; 16613)
[2023-07-28T14:21:56.052+0200] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-28T14:21:56.071+0200] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
